name: animated_grow
description: "AnimatedGrow is awesome and useful library of animation. It will give you the moves you really wanted."
version: 0.0.1
repository: https://github.com/hamhoney/animated_grow

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter