name: animated_grow
description: "A new Flutter project."
version: 0.0.1
repository: https://github.com/hamhoney/animated_grow

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter